kind = "web"
  previewPath = "/"
  title = "App"
  version = "1.0.0"

  [[services]]
  localPort = 5000
  name = "Start application"
  paths = ["/"]

  [services.env]
  PORT = "5000"

  [services.development]
  run = "node /home/runner/workspace/server.js"
  